### ISSUE TITLE
Add "Minimum" stakeholder score

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#103]
Next to its "Ambition" score, the stakeholder also sets its "Minimum" score in the To Be tab. This field is also communicated to the MCMSMV module.

**Comment by andreasrudena** [comment]
Added in the dashboard and sent along to MCMSMV module

**Comment by VincentKamphuis** [comment]
Disable this functionality for now. We should define it's rol in the process first.

**Comment by andreasrudena** [comment]
Removed in 1.0.10
