### ISSUE TITLE
KPI ambition level/weight won't save in Facilitator mode

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#104]
I get an error when I'm setting KPI ambition levels and weights as a Facilitator. It does work when I login for a specific stakeholder.

![image](https://cloud.githubusercontent.com/assets/12395999/9497234/5a8a40a2-4c14-11e5-9e95-51b920b5773f.png)

**Comment by andreasrudena** [comment]
Should be fixed in 1.0.7
