### ISSUE TITLE
Combine Set ambition & Set weight in 1 tab

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#107]
Combine Set ambition & Set weight in 1 tab. Setting the weight to 0 removes the option to set an ambition score and "blanks" the score bar in the overview.

**Comment by andreasrudena** [comment]
1 tab? Do you mean in the same dialog window, and combine the two buttons "set ambition" and "set weight"?

**Comment by andreasrudena** [comment]
Fixed in 1.0.8

**Comment by andreasrudena** [comment]
Setting to zero is not removing kpi value.. reopening this

**Comment by andreasrudena** [comment]
Fixed in 1.0.10
