### ISSUE TITLE
KPI value shows as zero on the bar

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#109]
See:

![image](https://cloud.githubusercontent.com/assets/12395999/9542238/5088dbb6-4d6f-11e5-8bd6-86a1b44e2d0a.png)

(seems to work fine for other KPI's)

**Comment by andreasrudena** [comment]
Look into the sufficient and excellent. Excellent is zero and sufficient is 2000. So the value is less then sufficient. This is a bug but it means that extrapolating from larger to smaller value is not working. I'll look into it. If KPI value is above sufficient the bar will raise towards zero

**Comment by andreasrudena** [comment]
Should be fixed in 1.0.8
