### ISSUE TITLE
Can't save KPI ambition score (exception)

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#111]
I can't seem to save the Energy_label_Havensteder ambition score for Havensteder from the Facilitator mode. Works for all others.

![image](https://cloud.githubusercontent.com/assets/12395999/9574915/ada60252-4fcb-11e5-847c-12800bb2d29b.png)

**Comment by andreasrudena** [comment]
I think this is solved now?
