### ISSUE TITLE
Include description of quantitative KPI's in "Set ambition" pop-up

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#122]
E.g. 

Sufficient = 6 score = Streets get flooded by rainfall once every 10 years. Buildings get damaged due to excess rainfall once every 25 years.
Excellent = 10 score = Streets get flooded by rainfall once every 100 years. Buildings get damaged due to excess rainfall once every 500 years.

And include the KPI description as well: e.g. "CO2 emission in kg/year per Havensteder dwelling".

**Comment by andreasrudena** [comment]
Do you mean that stakeholders add their own descriptions of "sufficient" and "excellent"?

**Comment by VincentKamphuis** [comment]
No, all descriptions should be as provided by the facilitator in the "Select KPI" tab.

**Comment by andreasrudena** [comment]
Add in on qualitative KPI!

**Comment by andreasrudena** [comment]
Fixed in 1.0.10

**Comment by VincentKamphuis** [comment]
Could you add the KPI description to the To Be pop-ups? Something like:

![image](https://cloud.githubusercontent.com/assets/12395999/9927097/d31ab426-5d1b-11e5-889e-3d5687acc318.png)

For both quantitative and qualitative KPI's?

**Comment by andreasrudena** [comment]
Fixed in 1.0.11

**Comment by VincentKamphuis** [comment]
Could you add the 6/10 descriptions for quantitative KPI's?

![image](https://cloud.githubusercontent.com/assets/12395999/9936275/68270a62-5d5b-11e5-973b-99c75161c67f.png)

**Comment by andreasrudena** [comment]
Cannot reproduce this, the descriptions work for me..

**Comment by andreasrudena** [comment]
I think this works now, at least for me. Otherwise, reopen!
