### ISSUE TITLE
Set KPI for all stakeholders on "disabled"

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#126]
Currently, when a KPI is set to disabled for the As Is situation or an Alternative, this KPI is only set to disabled for the Facilitator.

This KPI should be set to disabled for all stakeholders.

An example is the current configuration, in which 3 KPI's are disabled for the As Is situation. But in the output for the MCMSMV module, this KPI is only set on disabled for the Facilitator, instead of for all stakeholders.

**Comment by andreasrudena** [comment]
Could be fixed, at least in mcmsmv-data. Try this out now and reopen this if adjustments are needed.
