### ISSUE TITLE
Different KPI name for stakeholder communication

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#127]
Do we want to have an additional name for every KPI, used in communication between the stakeholders, but different from the current name, which is (and will continue to be) used for communication between the different IDSS components.

Relates to issue https://github.com/ecodistrict/IDSSDashboard/issues/94 and the discussion on data set-up.

**Comment by andreasrudena** [comment]
This is also related to #75. When adding edit functionality to KPI definition, this will be fixed, because changing the "technical" name automatically is not an option.
