### ISSUE TITLE
Extrapolation to negative KPI values

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#128]
Currently, the linear relation between 6 (sufficient) and 10 (excellent) may extrapolate to negative values, even if the KPI is positively defined. An example is:

![image](https://cloud.githubusercontent.com/assets/12395999/9846732/4835b296-5ad4-11e5-9e35-483408cfd9d9.png)

How to deal with this? Make another interpolation between 6 (Sufficient) and score 1 = 0? Or keeping score zero below the score for which the extrapolation results in zero?

Relates to: https://github.com/ecodistrict/IDSSDashboard/issues/76

**Comment by andreasrudena** [comment]
The KPI configuration needs to be flexible, for example a checkbox to allow negative numbers. Or there could be an optional range for the KPI, so setting the min value to zero will prevent it from extrapolate negative. Later we can also add the different scales in #76.

**Comment by andreasrudena** [comment]
Checkbox for "Allow negative" is added in 2.2.5
