### ISSUE TITLE
Sufficient shows as "not set" in Set Ambition pop-ups

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#130]
For qualitative KPI's, see:

![image](https://cloud.githubusercontent.com/assets/12395999/9928134/329b40b6-5d24-11e5-866d-7833dc2e0a39.png)

**Comment by andreasrudena** [comment]
Could not reproduce this. I can see that it is missing in this case, but I don't know why. It sets sufficient score 6 on my qualitative test KPIs.

**Comment by andreasrudena** [comment]
Maybe due to older data before update. I think it works now, otherwise reopen!
