### ISSUE TITLE
Green Area per Capita KPI (manually inputed): AS IS value's bar 

### ISSUE THREAD

**Issue by blancapedrola** [ecodistrict/IDSSDashboard#139]
The measurment bar starts with a negative value. This is not possible, since the minimum value is 0. Is it possible to change this to start from 0?
![bar](https://cloud.githubusercontent.com/assets/9248364/10490131/b0537f6a-729f-11e5-9957-94a6039c2b4b.jpeg)

**Comment by andreasrudena** [comment]
#143 Duplicate
