### ISSUE TITLE
Bar values in AS IS Energy Module

### ISSUE THREAD

**Issue by blancapedrola** [ecodistrict/IDSSDashboard#143]
Is it possible that the bar starts at 0? It doesn't make sense a negative value in this case. Thanks. See atta
![bar2](https://cloud.githubusercontent.com/assets/9248364/10515589/6c98d15c-7354-11e5-8458-8c6201821397.jpeg)
ched image.

**Comment by andreasrudena** [comment]
I can't find the issue now, but this already exists and should be connected to an existing issue. Both negative and zero are needed, so we should have an option to select per KPI if it should not be lower than zero or follow the extrapolation.

**Comment by andreasrudena** [comment]
Duplicate #128
