### ISSUE TITLE
KPI score not saved in develop alternatives

### ISSUE THREAD

**Issue by vsjoberg** [ecodistrict/IDSSDashboard#150]
Hi!

When I try to set a manual score for a KPI in an alternative the score isn't saved and I can't push the back button. If I set the score and then click on something else and then returns to the alternative screen it is not saved.

**Comment by andreasrudena** [comment]
Thanks for reporting! I didn't see the issues, because somehow I opted out for email notifications on new issues. 

This bug must have been solved in the latest version, I cannot reproduce it.
