### ISSUE TITLE
Remove irrelevant KPI:s in "assess alternatives"

### ISSUE THREAD

**Issue by vsjoberg** [ecodistrict/IDSSDashboard#163]
When we are in the assess alternatives screen and click on a alternative all of the KPI:s that are used in the project will pup up even though the alternative doesn't use them. We would like the ability to clean this up - i.e. remove irrelevant KPI:s. otherwise there is so much happening on the screen so it is hard to focus

**Comment by andreasrudena** [comment]
What about this?
1. Hide disabled KPIs by default
2. Add a "Show disabled KPIs"-button

**Comment by vsjoberg** [comment]
Sounds good!


Vänliga hälsningar


Viktor Sjöberg
Civilingenjör / Energi- & miljöspecialist
_______________________

White arkitekter AB
Östgötagatan 100, box 4700
116 92  Stockholm

dir    08 402 26 22
vxl    08 402 25 00
sms 070 626 07 64

viktor.sjoberg@white.se
www.white.se

**Comment by andreasrudena** [comment]
Fixed in version 2.2.10.

Click a KPI and "disable" it in assess alternatives screen. Now a button exists in the KPI list to toggle disabled KPIs. (only visible if any KPI are disabled).
