### ISSUE TITLE
Cannot login (bug?)

### ISSUE THREAD

**Issue by sverbeke** [ecodistrict/IDSSDashboard#49]
I cannot login to the dashboard (tested in Chrome and IE)

I keep stuck on the 'Log in to IDSS Dashboard-screen', asking for my email and password.
Upon  clicking 'log in', nothing happens. 
(also: if I fill in faulty fields, I do not get a response, but if I leave a field blank, I get a warning).

Despite this, in Chrome I see my name in the upper right corner, and I can choose to logout, so somehow I must be logged in to the dashboard?
I can see the buttons 'as is', etc in the top, but clicking these all keep me stuck on the login page.

**Comment by andreasrudena** [comment]
Yes the error messages are not existing. This is something I should add already next version! 
Also when logging out the routing doesn't work..

So if you click "log out" and refresh page it should work to login?

**Comment by andreasrudena** [comment]
I just tested to login with "your" account: stijn@idssdashboard.com sent by email, and it worked

**Comment by sverbeke** [comment]
Yes, it works now after loggin out. At least in Chrome.
In IE(11.0.18) I had some troubles, even after closing and reopening IE: I saw the button 'Create new process', then a map for half a second, and then I got stuck at the login screen. After hitting Shift-F5, I managed to login.

**Comment by andreasrudena** [comment]
Yes, I also heard there where more problems with IE. I test continuously Chrome and Firefox, so that are currently the featured browsers. If IE support is important I could prioritize that, at least find the problems to see if they are easy to fix.
