### ISSUE TITLE
Spinner for the MCMSMV button is not necessary 

### ISSUE THREAD

**Issue by mkeus** [ecodistrict/IDSSDashboard#55]
When clicking on the MCMSMV button the spinner is displayed and waiting for a success message. I don't think this is necessary, it is a fire and forget action. The receiver does not have to acknowledge this, and there's no error handling taken place on this, so the spinner has no meaning.

So i suggest to make it a button without a spinner/cursor waiting for an answer.

**Comment by andreasrudena** [comment]
Removed in version 1.0.2
