### ISSUE TITLE
Unit only at end of the score bar

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#57]
Put unit only at the end of the score bar, not at every axis point.

**Comment by VincentKamphuis** [comment]
![image](https://cloud.githubusercontent.com/assets/12395999/8156485/55325464-134d-11e5-9a02-cdd4f1cf6a8a.png)

**Comment by andreasrudena** [comment]
End of score bar was a bit tricky, I removed from axis and put unit below. Hopefully that is clear enough.
