### ISSUE TITLE
No select module command is sent when changing from one module to another.

### ISSUE THREAD

**Issue by Joma564** [ecodistrict/IDSSDashboard#61]
A select module command is sent when changing from no module to a module for a selected kpi. But when chaning from one module to another no message is sent. => no input specificaton for the new module.

**Comment by andreasrudena** [comment]
The select module message should now be sent every time you press 'OK' in the configure KPI dialog and a module is set in the drop down. Note that in the current version you may have to press ok several times before you see the blue message that selectModule was sent.
