### ISSUE TITLE
When a Calculation button is pressed, it sends 'previous' input

### ISSUE THREAD

**Issue by ReinierNL** [ecodistrict/IDSSDashboard#62]
When a Calculation button is pressed, it sends input that should have been sent the previous time.
It is as if there is a queue with requests, where the new request is placed in the queue and the one that was in the queue is sent.
In other words, when I press the Calculate button for the second time, the proper request is sent to the module.

**Comment by andreasrudena** [comment]
It seems like this is an issue for the IMB connector, I'll create an issue there.

**Comment by andreasrudena** [comment]
This should be fixed in the new IMB version of node.js client
