### ISSUE TITLE
Discussion needed about alternatives, variants etc.

### ISSUE THREAD

**Issue by SanderSchaminee** [ecodistrict/IDSSDashboard#7]
We have to make sure that we are all on the same page here. What is an alternative or a variant and how should the dashboard reflect this? How should a user define these in the GUI and how should they be compared in a multi-criteria/stakeholder tool?

**Comment by andreasrudena** [comment]
Closing this. Right now contexts are not supported, so variants are not supported. There are only alternatives in the dashboard. When contexts are added we can review this issue.
