### ISSUE TITLE
Connecting KPI scores to corresponding module output KPI's

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#71]
Link "As Is" and "Alternative" KPI scores to the corresponding module output KPI's. Can we use the KPI name and the Variant ID?

**Comment by andreasrudena** [comment]
Yes, variantId and kpiId makes it possible to distinguish "As Is" and all the alternatives from each other for a certain KPI result when the module returns the result. moduleId and userId is also required in module output.
