### ISSUE TITLE
Use priority (again) in Db flow

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#72]
Use priority (again) in the Dashboard flow. An alternative would be to use priorities only in the MCMSMV module.

**Comment by andreasrudena** [comment]
I think it is a good idea to add it to the dashboard and send it along to the MCMSMV module. The MCMSMV module should send back any updates that is made there to the dashboard

**Comment by andreasrudena** [comment]
Added weights to dashboard, so I close this
