### ISSUE TITLE
Show stakeholder role in the Db flow

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#73]
Show (signed in under) stakeholder role (clearly) in the Db flow.

**Comment by andreasrudena** [comment]
I am thinking that in the new version, the facilitator never sign in as a stakeholder. If the user does any action as a stakeholder that is shown in a drop down like in current 'To be' page. If you think that is enough we can close this issue for now.

**Comment by VincentKamphuis** [comment]
Agree.
