### ISSUE TITLE
Edit KPI/alternative definitions

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#75]
Add the option to edit KPI and Alternative definitions in the KPI database.

**Comment by VincentKamphuis** [comment]
High priority for me as this would be a major time saver.

**Comment by VincentKamphuis** [comment]
An edit in the KPI database would be reflected throughout the Dashboard configuration, so: also in the 'KPI's set for this decision process.'

**Comment by andreasrudena** [comment]
Added in 1.0.11

**Comment by andreasrudena** [comment]
Yes, the reflected change to process must be optional. There is a checkbox when you edit a KPI to also update the already selected KPI in the process.
