### ISSUE TITLE
Uncouple "Not Applicable" between situations

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#77]
Currently, when a KPI is disabled for the "As Is" situation (e.g. investment costs are zero), the KPI is also disabled for the "To Be" situation and the "Alternatives". This shouldn't be the case. In this situation, being disabled in the "As Is" situation should still allow scores (investment costs) to be defined for the other situations.

**Comment by andreasrudena** [comment]
Should be fixed in 1.0.3

**Comment by VincentKamphuis** [comment]
This doesn't seem to be fixed yet: disabling a KPI in one alternative makes it n/a for all situations in the "Compare alternatives" tab.

**Comment by andreasrudena** [comment]
I forgot to change the "Compare alternatives" tab, should be fixed in 1.0.5
