### ISSUE TITLE
"Martijn" shows up as a stakeholder

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#79]
"Martijn" shows up as a stakeholder in the "Compare Alternatives", because he defined two KPI's. This shouldn't be the case.

![image](https://cloud.githubusercontent.com/assets/12395999/8156568/e1b25c04-134d-11e5-93fa-b256a8f331ef.png)

**Comment by andreasrudena** [comment]
This should be fixed in 1.0.3, BUT all KPIs that where defined by another user must be deselected ("not used in the process") and selected again.
