### ISSUE TITLE
Every KPI "initializing"

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#80]
After redefining the PV KPI and coupling to the PV module, I see the following:

![image](https://cloud.githubusercontent.com/assets/12395999/8156646/70d40d60-134e-11e5-853f-003b07af4f3d.png)

Refreshing fixes the problem.

**Comment by andreasrudena** [comment]
I cannot reproduce this. It could be something from the old data, before the 1.0.2 version that caused this. If pressing calculate, and something goes wrong with the calculation (no response) then the status will be "initializing" forever (this is something that needs to be fixed, the initialization phase should be limited).

**Comment by andreasrudena** [comment]
Lets reopen this if we experience it again.
