### ISSUE TITLE
Calculating KPI doesn't work

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#82]
The "refreshing" strategy also doesn't work this time.

![image](https://cloud.githubusercontent.com/assets/12395999/8156890/98ee52e0-1350-11e5-81f7-42a47e62b1f8.png)

**Comment by VincentKamphuis** [comment]
Maybe (probably?) this concerns the "all modules already connected need to do a small adjustment, that is to send along the 'userId' property that is coming from the dashboard on every response except the 'getModules'."

**Comment by andreasrudena** [comment]
Yes, but it could also be the messaging problem. Keep pressing the stop / calculate button to make sure the message really gets sent. There should be a blue notification saying that "Module sent moduleResult".

**Comment by VincentKamphuis** [comment]
Works again (for the PV module) with the (small) adjustment to the module.
