### ISSUE TITLE
Stakeholder login doesn't work

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#84]
I cannot login with Stakeholder accounts. 

![image](https://cloud.githubusercontent.com/assets/12395999/8228824/2fbcb1a4-15b2-11e5-9588-33ccf05367d9.png)

**Comment by VincentKamphuis** [comment]
What I would like to do is to disable "irrelevant" KPI scores for several stakeholder/alternative combinations. An alternative would be to set the priorities for these scores to a minimum (1 out of 5) in the MCMSMV module.

**Comment by andreasrudena** [comment]
The login for stakeholder is disabled, the idea was that the facilitator never should need to login to the stakeholder accounts and that all configuration should be done in the facilitator account. My suggestion is to add the dropdown on every alternative (to change between stakeholders), like it is now on the as-is page. Create a new feature request?
