### ISSUE TITLE
KPI scores don't show up for stakeholders

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#85]
KPI scores for the "As Is" and "Alternatives" are not (can not be?) defined for the Stakeholders. The scores should be the same as the ones for the Facilitator.

![image](https://cloud.githubusercontent.com/assets/12395999/8229047/cc2bae5e-15b3-11e5-8410-3961776a4801.png)

**Comment by andreasrudena** [comment]
Facilitator values are now added to stakeholder
