### ISSUE TITLE
Compare alternatives tab for large numbers of KPI's

### ISSUE THREAD

**Issue by VincentKamphuis** [ecodistrict/IDSSDashboard#89]
The Compare Alternatives tab doesn't seem to function properly for large numbers of KPI's. When I used a larger set of KPI's (before) not all KPI's showed up in the overview. Also the following graph gets messed up:

![image](https://cloud.githubusercontent.com/assets/12395999/8355367/1b9344de-1b4f-11e5-9051-ed435e8adffa.png)

**Comment by andreasrudena** [comment]
Fixed 1.0.5 for KPI table, it will expand for larger sets. Problem with KPIs not showing up could not be reproduced, but when no user (facilitator or stakeholder) put any value on the KPI the KPI is not shown (there are no values). This could be changed if necessary.
